---
title: "Research"
---
<script>
function hide_buttons(abstract) {
    var x = document.getElementById(abstract);
    if (x.style.display === "none") {
        x.style.display = "block";
    } else {
        x.style.display = "none";
    }
}
</script>

**Dynamic Spatial Competition in Early Education: an Equilibrium Analysis of the Preschool Market in Pennsylvania** ([Draft](content/bodere_jmp.pdf))

<button class="button_that_looks_like_link" role="button" onclick="hide_buttons('abstract_preschool')">Abstract</button>
<div id="abstract_preschool" style="display:none;">
High-quality preschool is one of the most cost-effective educational interventions, yet the United States invests little in early childhood education. Recent policy discussions call for increasing preschool enrollment and raising the quality provided, especially for disadvantaged children, but equilibrium responses of private providers which make up most of the market generate trade-offs between these objectives. Supply expansion may lower incentives to invest in quality, and price responses to demand subsidies can increase the costs faced by non-subsidized parents. This paper develops a dynamic model of the preschool market to evaluate the effectiveness of policies at achieving these objectives. The model nests a static equilibrium model of spatial competition and preschool choice within a dynamic model of providers' entry, exit and quality investments. I estimate this model using data on the universe of child-care centers in Pennsylvania. I use the model to simulate the aggregate and distributional consequences of proposed approaches to early education expansion. I find that policies focused on expanding supply raise access but decrease the quality children attend due to parents' value for proximity. Demand subsidies generate  market expansion, but on their own do not create sufficient incentives for providers to invest in quality. Among the simulated policies, the most cost-effective at expanding high-quality enrollment combine demand subsidies targeted to low-income families with financial support to providers serving disadvantaged children. These policies increase access by reducing exit of providers, and expand high-quality enrollment for low-income children through subsidies. In addition, these targeted policies generate spillovers to the educational quality of non-targeted families by creating incentives for centers to invest in quality.
</div> 

</br>
**Wait Times for Surgery in the U.S.: Measurement and Allocative Efficiency in Private Insurance**
with [<span style="font-weight: normal">Michael Dickstein</span>](http://www.michaeljdickstein.com/) and [<span style="font-weight: normal">Guillaume Fréchette</span>](http://people.cess.fas.nyu.edu/frechette/html/econ.htm)

<button class="button_that_looks_like_link" role="button" onclick="hide_buttons('abstract_wait')">Abstract</button>
<div id="abstract_wait" style="display:none;">
In the face of limited health care resources, waiting time often serves as a rationing mechanism
in health systems around the world. We evaluate the efficiency and equity consequences
of rationing via queues in the context of surgical care. Focusing on the U.S. private insurance
market, we first develop a new measure of wait time that captures the complete patient
trajectory—including visits for primary care, laboratory testing, and medical imaging—along
the path to surgery. Exploiting exogenous variation due to weekly congestion within a patient’s
insurance network, we show that patients who wait a month more spend 1% more on hospital
care, are 1.1% more likely to be readmitted to a hospital, and fill 2.6% more opioid prescriptions
in the six months following a surgery. The effects of waiting on hospital outcomes are more
pronounced for surgeries that follow a cancer diagnosis, while the effects on opioids are largest
for orthopedic surgeries. We further quantify misallocation of wait times relative to the planner’s
ideal. We identify heterogeneous effects of waiting, but those patient groups who suffer the
highest costs from delay do not uniformly experience shorter waits. We illustrate how positive
prioritization—say, by providing physicians information on the treatment effects of waiting by
patient type—could reduce payments to hospitals and improve patient health outcomes.
</div> 

</br>
**News Media Concentration and Content Diversity**
with [<span style="font-weight: normal">Nicolas Longuet Marx</span>](https://nicolaslonguetmarx.github.io/) and [<span style="font-weight: normal">Marguerite Obolensky</span>](https://margueriteobolensky.github.io/)

<button class="button_that_looks_like_link" role="button" onclick="hide_buttons('abstract_media')">Abstract</button>
<div id="abstract_media" style="display:none;">
The rise in political polarization over the recent years has fostered scrutiny of the structure of the news industry’ s influence on political outcomes. How should policymakers regulate news producers when they value news diversity and large publishers shape the ideological landscape? To answer this question, we develop an empirical model of competition for readership and advertisers between news producers. We recover the topic content and ideological positions of 200 major U.S. daily newspapers using recent advances in Natural Language Processing on millions of published articles. We find that over the period 2007-2017, the median newspaper in our sample got closer to the ideology of the Democratic party. Second, we embed these topics and ideal points in a demand model for differentiated products with heterogeneous readers. Our model shows that rich readers lean democrat and consume more news about social and political questions while the elderly are more conservative and care more about local news. Using the estimated demand model and data on advertising contracts and readership, we can recover the cost of producing each type of content. Given this model of news supply, we intend to use our framework to provide recommendations on antitrust rules weighing both consumer welfare and ideological diversity.
</div> 

</br>
**Inefficiencies in Local Infrastructure: Evidence from Drinking Water in California**
with [<span style="font-weight: normal">Giulia Brancaccio</span>](http://www.giulia-brancaccio.com/) and [<span style="font-weight: normal">Karam Kang</span>](https://karamkang.github.io/)

<button class="button_that_looks_like_link" role="button" onclick="hide_buttons('abstract_water')">Abstract</button>
<div id="abstract_water" style="display:none;">
This paper measures potential inefficiency in California's drinking water infrastructure and investigates its causes and welfare consequences, drawing on a novel dataset that integrates drinking water investments, system performance, local politics, and housing market. 
Using eligibility thresholds for federal funds, we demonstrate that weak electoral accountability contributes to infrastructure underinvestment and diminishes the effectiveness of federal funding programs. 
We then build a dynamic model of local officials' infrastructure investment decision-making, which reveals that investment inefficiencies can arise when officials prioritize certain constituencies and when residents have varying preferences for water quality, particularly under the constrained rate structures common to water and many regulated utilities. We estimate residents' valuations of water quality improvements and officials' preferences over constituents, and using the estimated model, we quantify the extent of investment inefficiencies and assess the potential impacts of policy solutions.
</div> 


